spring:
  application:
    name: zuul
    
server:
  port: 8011
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

api:
  login:
    url:
      path: /users-ws/api/v1/users/login
  registration:
    url:
      path: /users-ws/api/v1/users
  h2console:
    url:
      path: /users-ws/h2-console/**

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: secrettoken