server:
  port: 8761
    
spring:
  application:
    name: pictogramDiscoveryService
       
eureka:
  client:
    register-with-eureka: false #Please do not register with yourself
    fetchRegistry: false #Please do nt search for other registry nodes to connect to.
    service-url:
      defaultZone: http://localhost:8761/eureka #Default URL for teh Eureka server.